steps:
        - name : 'gcr.io/cloud-builders/docker'
          args : ['build', '-t', 'gcr.io/hellonodejs/hellonodejs-test', '.']
          timeout : 500s
          waitFor: ['-']
        - name : 'gcr.io/cloud-builders/docker'
          args : ['push', 'gcr.io/hellonodejs/hellonodejs-test']
options:
        machineType: 'N1_HIGHCPU_8'
timeout : 1000s

